---
general_commands:
  # Configure macOS black wallpaper
  - osascript -e 'tell application "Finder" to set desktop picture to POSIX file "'"/System/Library/Desktop Pictures/Solid Colors/Black.png"'"'
  # Set Firefox as default browser
  - /opt/homebrew/bin/defaultbrowser firefox
  # Set display poweroff on battery 15 min
  - pmset -b displaysleep 15
  # Set display poweroff on power adapter 45 min
  - pmset -c displaysleep 45
  # Update tldr pages
  - tldr -u
  # Set dynamic hostname
  - scutil --set ComputerName "{{ dynamic_hostname }}"
  - scutil --set LocalHostName "{{ dynamic_hostname }}"
  - scutil --set HostName "{{ dynamic_hostname }}"
