---
homebrew_formulas:
  # DONT REMOVE defaultbrowser + dockutil
  defaultbrowser:
  dockutil:
  neovim:
  fish:
  coreutils:
  curl:
  fzf:
  btop:
  tmux:
  fastfetch:
  trash-cli:
  eza:
  zoxide:
  tlrc:
  omlx:
  mas:
  superfile:
  syncthing:
homebrew_casks:
  discord:
  bitwarden:
  firefox:
  obsidian:
  webex:
  citrix-workspace:
  kitty:
  vlc:
  spotify:
  font-hack-nerd-font:
  nikitabobko/tap/aerospace:
  libreoffice:
  battery:
  protonvpn:
  docker:
  rustdesk:
  vorssaint:
  ungoogled-chromium:
  nextcloud:
homebrew_taps:
  dail8859/notepadnext:
  jundot/omlx:
    url: https://github.com/jundot/omlx
