---
- name: Insert fish shell at the top of the shell list
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: '/opt/homebrew/bin/fish'
    insertbefore: '^/bin/bash'
    backup: true

- name: Change default shell to fish for the current user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /opt/homebrew/bin/fish
    generate_ssh_key: "{{ generate_ssh_key | default(false) }}"
    ssh_key_type: ed25519
    update_password: on_create
    ssh_key_file: .ssh/id_ed25519

- name: Copy sudo local template for sudo Touch ID
  become: true
  ansible.builtin.copy:
    src: /etc/pam.d/sudo_local.template
    dest: /etc/pam.d/sudo_local
    mode: preserve

- name: Enable sudo with Touch ID
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo_local.template
    regexp: '^#\s*(auth\s+sufficient\s+pam_tid\.so)$'
    line: 'auth       sufficient     pam_tid.so'
    backrefs: true
    backup: true

- name: Check if device has a battery
  ansible.builtin.command: ioreg -rc AppleSmartBattery
  register: battery_check
  changed_when: false
  failed_when: false

- name: Check if battery CLI is installed
  ansible.builtin.command: which battery
  register: battery_which
  changed_when: false
  failed_when: false

- name: Warn if battery CLI not yet initialized
  when: battery_check.stdout | length > 0 and battery_which.rc != 0
  ansible.builtin.debug:
    msg: "Battery app needs to be opened once manually to initialize the CLI daemon."

- name: Set battery charge limit to maintain 70% - 80%
  when: battery_check.stdout | length > 0 and battery_which.rc == 0
  ansible.builtin.command: battery maintain 70-80

- name: Get hardware info
  ansible.builtin.command: system_profiler SPHardwareDataType
  register: hardware_info
  changed_when: false

- name: Set dynamic hostname
  ansible.builtin.set_fact:
    dynamic_hostname: >-
      {{ hardware_info.stdout | regex_search('Model Name: (.+)', '\1') | first | lower | replace(' ', '') -}}
      {{ hardware_info.stdout | regex_search('Chip: Apple (M\d+)', '\1') | first | lower -}}
      {{ hardware_info.stdout | regex_search('Memory: (\d+) GB', '\1') | first -}}gb

- name: Run general commands
  become: true
  loop: "{{ general_commands }}"
  loop_control:
    loop_var: general_commands_loop
    label: "{{ general_commands_loop }}"
  ansible.builtin.command: "{{ general_commands_loop }}"

