---
- name: Run homebrew install tasks
  ansible.builtin.include_tasks:
    file: homebrew.yml

- name: Run mas (Mac App Store) install tasks
  ansible.builtin.include_tasks:
    file: mas.yml

- name: Run MacOS defaults tasks
  ansible.builtin.include_tasks:
    file: osx_defaults.yml

- name: Run MacOS general tasks
  ansible.builtin.include_tasks:
    file: general.yml

